# Jupyter formatting syntax
bold is ** before and after
italic is _ or * before and after
underline is < ins> < /ins>
adding an image in html: < img src="filename" align = "right/left/center" width=### height=### / >


# Manipulating Data With Pandas <img src="images/SWC22-Pandas.PythonPandasLogo.jpg" align = "right" width=200 height=200/>
- Pandas is a data analysis library built on top of NumPy.
- Pandas provides data structures and operations for manipulating data using DataFrames
- DataFrames are multidimensional arrays with attached row and column labels.
- DataFrames can include heterogeneous types and/or missing data.
- Pandas also provides functions for handling data in a similar fashion to database frameworks and spreadsheet programs.



In [77]:
# use NumPy and Pandas
import numpy as np
import pandas as pd
print("Pandas version is", pd.__version__)

Pandas version is 1.4.2


# The Series Object
- A Pandas **Series** is a one-dimensional array of indexed data. It can be created from a list or array.
    - A Series wraps both a sequence of values and a sequence of indices, which can be used to access with the values and index attributes.
    - The values are simply a familiar NumPy array


In [78]:
atad = pd.Series([0.52, 0.8, 0.63, 4.0], index = ['a', 'b', 'c', 'd'])
print(atad)
print()
print(atad.values)

a    0.52
b    0.80
c    0.63
d    4.00
dtype: float64

[0.52 0.8  0.63 4.  ]


# The Series Index
- The Series index is an array-like object of type pd.Index
    - Like with a NumPy array, data can be accessed by the associated index using square-bracket notation
    - The Pandas Series is much more general and flexible than the one-dimensional NumPy array that it emulates.


In [79]:
data = pd.Series([0.25, 0.5, 0.79, 1.0])
data

0    0.25
1    0.50
2    0.79
3    1.00
dtype: float64

In [80]:
#index of the data series
data.index

RangeIndex(start=0, stop=4, step=1)

In [81]:
#the element at index 1
data[1]

0.5

In [82]:
#a slice of a series (start:stop)
data[1:3]

1    0.50
2    0.79
dtype: float64

# Python Dictionaries and Pandas Series
- A Pandas Series is similar to a specialized Python dictionary. 
    - A dictionary maps arbitrary keys to a set of arbitrary values; a Series maps typed keys to a set of typed values.
    - The type information of a Pandas Series is much more efficient than Python dictionaries for certain operations.
- Construct a Series object directly from a Python dictionary:


In [83]:
#create a dictionary of key:value pairs
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population_dict

{'California': 38332521,
 'Texas': 26448193,
 'New York': 19651127,
 'Florida': 19552860,
 'Illinois': 12882135}

In [84]:
#create a Pandas series from a Python dictionary
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [85]:
#notice the difference between printing the Python dictionary and printing the Pandas Series
#there is an implied for:each loop to print each element on a separate line.
print("Dictionary:")
print(population_dict)
print("\nSeries:")
print(population)


Dictionary:
{'California': 38332521, 'Texas': 26448193, 'New York': 19651127, 'Florida': 19552860, 'Illinois': 12882135}

Series:
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64


### Dictionary-style item access can be used with a Series:



In [86]:
population['California']

38332521

- Unlike a dictionary, the Series also supports Numpy array-style operations such as slicing:

In [87]:
population['California':'New York']

California    38332521
Texas         26448193
New York      19651127
dtype: int64

# Creating a Series
- Creating a Series is almost always some form of
            pd.Series(data, index = index)
- where index is an optional argument, and data can be one of many entities (e.g., list, dictionary, Numpy array).

In [88]:
# simple scalar series
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [89]:
# scalar series, fill with 5's and specify index
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [90]:
# simple dictionary-based series
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [91]:
# populate using only specified keys (by index)
print(pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2]))

3    c
2    a
dtype: object


# DataFrames
- The DataFrame can also be thought of either as a generalization of a NumPy array, or as a specialization of a Python dictionary.
- A DataFrame is comparable to a two-dimensional array with both flexible row indices and flexible column names. 
- Just as you might think of a two-dimensional array as an ordered sequence of aligned one-dimensional columns, you can think of a DataFrame as a sequence of aligned Series objects.



### Construct a new area Series which parallels the population Series created earlier, then create a two-dimensional DataFrame using those objects

In [92]:
#recall the population_dict from above
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}

In [93]:
#and the Pandas Series created from that dictionary
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [94]:
#create a new area dictionary for the same states
area_dict = {'California': 423967,
             'Texas': 695662,
             'New York': 141297,
             'Florida': 170312, 
             'Illinois': 149995}

In [95]:
#create a Pandas Series from the area dictionary
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [96]:
#create a DataFrame from the two Series
states = pd.DataFrame({'population': population,
                       'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

### DataFrame attributes

- DataFrames have an index and a column attribute

In [97]:
#index refers to the row headings
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [98]:
states.columns

Index(['population', 'area'], dtype='object')

In [99]:
#DataFrames use colum values as indices to a series
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [100]:
### A DataFrame from a list of Dictionaries

In [101]:
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
data



[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [102]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

## Missing Values
- Missing values are filled with NaN ("not-a-number")
- This behavior is important; in data science missing values can impact analytical results and should be dealt with consistently
- https://towardsdatascience.com/navigating-the-hell-of-nans-in-python-71b12558895b


In [103]:
data=[{'a': 1, 'b': 2}, 
      {'b': 3, 'c': 4}]
data

[{'a': 1, 'b': 2}, {'b': 3, 'c': 4}]

In [104]:
pd.DataFrame(data)

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

# A DataFrame from a 2D Array
- Given a two-dimensional array of data, a DataFrame can be created with any specified  column and index name.
    - If the names are omitted, an integer index will be used for each


In [105]:
pd.DataFrame(np.random.rand(3, 2),
      columns=['foo', 'bar'],
      index=['a', 'b', 'c'])

foo       bar
a  0.334296  0.391181
b  0.529694  0.419342
c  0.508777  0.996837

# The Pandas Index is an Object
- Both the Series and DataFrame objects in Pandas contain an explicit index that lets you reference and modify data
- A Pandas Index is itself an object that may contain repeated values
- It can be thought of either as an immutable array or as an ordered set (technically a multiset -- a set which allows multiple instances of each of its elements)
- This has some interesting consequences in operations available on Index objects. 


In [106]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

## Array-like Behavior of a Pandas Index
- The Index object in many ways operates like an array. 
    - Indexing notation to retrieve values or slices
    - Index objects have many of the attributes familiar from NumPy arrays


In [107]:
ind[1]

3

In [108]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

## A Pandas Index is Immutable
- One difference between Index objects and NumPy arrays is that indices are immutable; they cannot be modified in place.
- This makes it safer to share indices between multiple DataFrames and arrays, without the potential for side effects from inadvertent index modification.


In [109]:
ind[1] = 0

TypeError: Index does not support mutable operations

## The Pandas Index as an Ordered Set
- Pandas objects are designed to facilitate operations such as joins across datasets
- The Index object follows many of the conventions used by Python’s built-in set data structure, so that unions, intersections, differences, and other combinations can be computed.


In [110]:
#create two index objects
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [111]:
#indA & indB --> intersection: the & usage is deprecated, use the intersection method

indA.intersection(indB)


Int64Index([3, 5, 7], dtype='int64')

In [112]:
# indA ^ indB --> symmetric difference ("exclusive OR"): the ^ usage is deprecated

indA.symmetric_difference(indB)

Int64Index([1, 2, 9, 11], dtype='int64')

In [113]:
# indA | indB  --> union: The | usage is deprecated

indA.union(indB)


Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

# Series as a Dictionary
- Like a dictionary, the series object provides a mapping from a collection of keys to a collection of values

In [114]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                index=['a', 'b', 'c', 'd'])

In [115]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [116]:
data['b']

0.5

### We can use dictionary-like expressions and methods to examine keys/indices and values

In [117]:
'a' in data

True

In [118]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [119]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

### Series objects can even be modified with a dictionary-like syntax
- As a dictionary can be extended by assigning to a new key, extend a series by assigning a value to a new index

In [120]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [121]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

# Series as a One-dimensional Array
- A series provides array-style item selection using the same basic mechanisms as NumPy array, including slices, masking, and fancy indexing

In [122]:
#slicing by explicit index
#NOTE: includes last index!!

data['a':'c']


a    0.25
b    0.50
c    0.75
dtype: float64

In [123]:
#slicing by implicit integer index
#NOTE: does NOT include the last index!

data[0:2]

a    0.25
b    0.50
dtype: float64

In [ ]:
#masking
data[(data > 0.3) & (data < 0.8)]

In [124]:
#fancy indexing -- non-continuous
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

# Indexers
### Pandas provides special <ins>indexer</ins> attributes that explicitly expose certain indexing schemes to help prevent confusion when indexing.

- Without using the indexers, given a specific index, indexing will use the Series index.
- Without using the indexers, slicing will use the Python-style index.


In [125]:
data = pd.Series(['a', 'b', 'c'], 
                 index=[1, 3, 5])


In [126]:
# explicit index
print(data[1])

a


In [127]:
# implicit index when slicing --> up to but not including the last index
print(data[0:2])

1    a
3    b
dtype: object


#### The loc attribute allows indexing and slicing that always references the explicit index

In [128]:
data.loc[1]

'a'

#### The iloc attribute allows indexing and slicing that always references the implicit Python-style index

In [129]:
data.iloc[1]

'b'

#### _The explicit nature of loc and iloc make them very useful in maintaining clean and readable code, especially in the case of integer indexes_

# DataFrame as Dictionary
- The individual series that make up the columns of the DataFrame can be accessed via dictionary-style indexing of the column name

In [130]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})

In [131]:
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [132]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [133]:
#we can use attribute-style access with column names that are strings

data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [134]:
#use the **is** operator to compare identities of each object

data.area is data['area']

True

In [135]:
data.pop('area')


California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [136]:
data.columns

Index(['pop'], dtype='object')

### Dictionary-style syntax can also be used to modify the DataFrame

In [137]:
#first, add back the column that was popped previously

data['area'] = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
data

pop    area
California  38332521  423967
Texas       26448193  695662
New York    19651127  141297
Florida     19552860  170312
Illinois    12882135  149995

In [138]:
#compute density and add the density column to the DataFrame

data['density'] = data['pop'] / data['area']

data

pop    area     density
California  38332521  423967   90.413926
Texas       26448193  695662   38.018740
New York    19651127  141297  139.076746
Florida     19552860  170312  114.806121
Illinois    12882135  149995   85.883763

# CHECK ON THIS!
## DataFrame as a Two-dimensional (2D) array
- The DataFrame can be viewed as an enhanced two-dimensional array
 - View the underlying data array using the ndarray **values** attribute

In [148]:
data.values

array([[3.83325210e+07, 4.23967000e+05, 9.04139261e+01],
       [2.64481930e+07, 6.95662000e+05, 3.80187404e+01],
       [1.96511270e+07, 1.41297000e+05, 1.39076746e+02],
       [1.95528600e+07, 1.70312000e+05, 1.14806121e+02],
       [1.28821350e+07, 1.49995000e+05, 8.58837628e+01]])

- Transpose the array using the **T** attribute


In [140]:
data.T

California         Texas      New York       Florida      Illinois
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

-The dictionary-style indexing of columns precludes simple treatment of DataFrames as NumPy arrays
 - e.g. passing a single index to an Numpy array accesses a row, passing a single index to a DataFrame accesses a column


In [147]:
#transpose again to put back into the original data frame
data.T

data

pop    area     density
California  38332521  423967   90.413926
Texas       26448193  695662   38.018740
New York    19651127  141297  139.076746
Florida     19552860  170312  114.806121
Illinois    12882135  149995   85.883763

In [149]:
data.values[0]

array([3.83325210e+07, 4.23967000e+05, 9.04139261e+01])

In [150]:
np_data = data.to_numpy()

np_data

array([[3.83325210e+07, 4.23967000e+05, 9.04139261e+01],
       [2.64481930e+07, 6.95662000e+05, 3.80187404e+01],
       [1.96511270e+07, 1.41297000e+05, 1.39076746e+02],
       [1.95528600e+07, 1.70312000e+05, 1.14806121e+02],
       [1.28821350e+07, 1.49995000e+05, 8.58837628e+01]])

In [151]:
np_data[0]

array([3.83325210e+07, 4.23967000e+05, 9.04139261e+01])

In [152]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

# Using Indexers with DataFrames
- As with Series, Pandas uses the loc and iloc indexers with DataFrames
 - Using iloc, the underlying array can be indexed as a simple NumPy array, but the DataFrame index and column labels are maintained in the result

In [155]:
#the index goes up to, but does not include, the endpoints
data.iloc[:3, :2]


pop    area     density
California  38332521  423967   90.413926
Texas       26448193  695662   38.018740
New York    19651127  141297  139.076746

In [160]:
#loc includes the endpoints
data.loc[:'Florida', :'area']


pop    area
California  38332521  423967
Texas       26448193  695662
New York    19651127  141297
Florida     19552860  170312

# Additional Indexing Conventions

- For DataFrames, indexing refers to <ins>columns</ins> and slicing refers to <ins>rows</ins>

In [163]:
data['Florida':'Illinois']

pop    area     density
Florida   19552860  170312  114.806121
Illinois  12882135  149995   85.883763

- Rows can also be accessed using row numbers

In [164]:
data[1:3]

pop    area     density
Texas     26448193  695662   38.018740
New York  19651127  141297  139.076746

-Direct masking operations are row-wise rather than column-wise

In [165]:
data[data.density > 100]

pop    area     density
New York  19651127  141297  139.076746
Florida   19552860  170312  114.806121

# Index Preservation
- Because Pandas is designed to work with NumPy, any NumPy ufunc will work on Pandas Series and DataFrame objects


In [166]:
df = pd.DataFrame(np.random.randint(0, 10, (3, 4)), columns=['A', 'B', 'C', 'D'])

df

A  B  C  D
0  5  7  3  0
1  6  0  9  0
2  1  8  5  8

In [167]:
newDF = 2 ** df

newDF

A    B    C    D
0  32  128    8    1
1  64    1  512    1
2   2  256   32  256

# Index Alignment in Series
- Pandas will align (combine) indices in the process of performing binary operations

In [168]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')

population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [169]:
area

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64

In [170]:
population

California    38332521
Texas         26448193
New York      19651127
Name: population, dtype: int64

-The result of a binary operation contains the union of indices of the two input objects
 - Any item for which one or the other does not have an entry is marked with NaN, or “Not a Number,” which is how Pandas marks missing data

In [173]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

- If using NaN values is not the desired behavior, we can modify the fill value using appropriate object methods in place of the operators. 


In [174]:
# Instead of population / area, call this:
population.divide(area, fill_value=1.0)


Alaska        5.802696e-07
California    9.041393e+01
New York      1.965113e+07
Texas         3.801874e+01
dtype: float64

# Index Alignment in DataFrames
- Index alignment takes place for both columns and indices when you are performing operations on DataFrames

In [175]:
A = pd.DataFrame(np.random.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A

A  B
0  14  6
1   8  7

In [176]:
B = pd.DataFrame(np.random.randint(0, 10, (3, 3)),
                 columns=list('BAC'))

B

B  A  C
0  5  2  0
1  3  6  1
2  5  5  1

In [178]:
B + A

A     B   C
0  16.0  11.0 NaN
1  14.0  10.0 NaN
2   NaN   NaN NaN

- Indices are sorted and aligned correctly irrespective of their order in the two objects
 - Notice in the cmbined DataFrame the columns are in alphabetical order


##### -  - - - - - - - - - - - - - - - - - - - - - - - - 

- As with Series, the object’s arithmetic methods can be used to pass any desired fill_value in place of missing entries


In [182]:
# calculate mean of all elements of A and use for fill
fill = A.stack().mean()

fill


8.75

In [183]:
A

A  B
0  14  6
1   8  7

In [184]:
B

B  A  C
0  5  2  0
1  3  6  1
2  5  5  1

In [181]:
A.add(B, fill_value=fill)

A      B     C
0  16.00  11.00  8.75
1  14.00  10.00  9.75
2  13.75  13.75  9.75

# Handling Missing Values
- Real-world data is rarely clean and homogeneous
 - Many datasets will have missing data
- Different data sources may indicate missing data in different ways
 - Using a mask
  - as a separate Boolean array
  - as a single bit in the data representation
 - Using a sentinel value
  - a data-specific convention, e.g. for missing integers use –9999 or some rare bit pattern
  - NaN (Not a Number) for missing floating point values 
   - NaN is part of the IEEE floating-point specification
- No universally common choice exists, different languages and systems use different conventions.
- Pandas uses sentinels for missing data, using two already-existing Python null values: the special floating-point NaN value, and the Python None object
 - This results in some side effects, but in practice is a good compromise.
- None is a "singleton" object – there can exist only one.
 - -- "The None keyword is used to define a null value, or no value at all. None is not the same as 0, False, or an empty string. None is a datatype of its own (NoneType) and only None can be None" 
https://www.w3schools.com/python/ref_keyword_none.asp


# Using None in NumPy
- Because None is a Python object, it cannot be used in any arbitrary NumPy/Pandas array, but only in arrays with data type 'object' (i.e., arrays of Python objects).


In [185]:
vals1 = np.array([1, None, 3, 4])
vals1


array([1, None, 3, 4], dtype=object)

In [186]:
vals1.dtype

dtype('O')

- dtype=object means that the best common type representation NumPy could infer for the contents of the array is that they are Python objects.
- Object arrays can be useful, but operations on the data will be done at the Python level, with much more overhead than the typically fast operations seen for arrays with native types
 - If you perform aggregations like sum() or min() across an array with a None value, you will generally get an error since operations between numbers and None are undefined


# Using NaN in NumPy
- The other missing data representation, NaN (acronym for Not a Number), is different; it is a special floating-point value recognized by all systems that use the standard IEEE floating-point representation.
 - NaN is specifically a floating-point value; there is no equivalent NaN value for integers, strings, or other types.
- NumPy uses a native floating-point type for arrays containing NaN.
 - Unlike the object array from before, this array supports fast operations pushed into compiled code.


In [187]:
vals2 = np.array([1, np.nan, 3, 4])
vals2


array([ 1., nan,  3.,  4.])

In [188]:
vals2.dtype

dtype('float64')

- "NaN is a bit like a data virus—it infects any other object it touches." 
 - [VanderPlas, Python Data Science Handbook]
- NaN values will propagate through numeric operations
 - The result of arithmetic with a NaN will be another NaN


In [190]:
1 + np.nan

nan

In [191]:
0 *  np.nan

nan

- Using aggregate functions with NaN values does not result in errors, but the results aren't very useful


In [192]:
vals2

array([ 1., nan,  3.,  4.])

In [193]:
vals2.sum()

nan

In [194]:
vals2.min()

nan

In [195]:
vals2.max()

nan

- NumPy provides special aggregations that will ignore these missing values:


In [196]:
vals2

array([ 1., nan,  3.,  4.])

In [197]:
np.nansum(vals2)

8.0

In [198]:
np.nanmin(vals2)

1.0

In [199]:
np.nanmax(vals2)

4.0

# NaN and None in Pandas
- Pandas is built to handle NaN and None nearly interchangeably, converting between them where appropriate



In [200]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

- When integer values are set to NaN or None, the data type is automatically up-cast to floating point
 - None is automatically converted to a NaN value


In [203]:
x = pd.Series(range(2), dtype=int)

x

0    0
1    1
dtype: int32

In [204]:
x[0] = None

x

0    NaN
1    1.0
dtype: float64

# Start on Slide 55