# Introduction to NumPy
-  __NumPy__ (Numerical Python) is pronounced NUM-py or sometimes NUM-pee
-  NumPy provides __arrays__ similar to Python __lists__, but with more efficient storage and better performance, 
particularly as the data grows larger.
-  NumPy arrays are the core of data science tools in Python

## Installing and Using NumPy
### Installing NumPy on Windows 10 using pip:
- For an "all-user" configuration, run CMDtool as admin user
- Navigate to install folder, e.g. assuming Python is installed in C:\Program Files\Python

     C:
     cd "\Program Files\Python"

- Update pip and setuptools first

        C:\Program Files\Python>python -m pip install --upgrade pip

        C:\Program Files\Python>pip install --upgrade setuptools

        C:\Program Files\Python>pip install numpy

In [37]:
# Importing numpy in a program
import numpy as np      # alias to np
print("NumPy version is", np.__version__)   # version check

NumPy version is 1.22.3


## Understanding Data Types in Python
- "Primitive" data types in Python (integers, floating point values, Booleans) are objects
    - Each object consists of an internal C-language structure which includes a reference count, a type encoding, a size attribute, and the actual value
    - These attributes make Python a dynamically typed (flexible) language, but also reduce performance
- In a Python list, each element is a self-contained object
    - When lists contain elements of the same data type, some internal information is redundant
    - List elements are randomly distributed throughout memory

## NumPy N-Dimensional Arrays
- A NumPy n-dimensional array (ndarray)  is a fixed-size, multidimensional container of items of the same type and size.
    - The number of dimensions and items in an ndarray is defined by its shape, which is a tuple of N non-negative integers that specify the sizes of each dimension.
- NumPy arrays store data as a contiguous block for efficiency ("dense" arrays).
    - The Python array module (Python 3.3 and later) provides a similar structure, but the NumPy ndarray provides additional operations.

## NumPy Arrays vs. Python Lists

<img src="images/SWC22-NumPy.python-list.numpy-array.png" align = "left" width=300 height=300 />

<img src="images/SWC22-NumPy.python-list.png" align = "left" width=400 height=400 />

# Creating NumPy Arrays from Lists
- ndarrays can be created from Python lists

In [38]:
# integer array:
npa = np.array([1, 4, 2, 5, 3])
print(npa)

# upcast integers to float
npa = np.array([3.14, 4, 2, 3])
print(npa)

# specify array element type
npa = np.array([1, 2, 3, 4], dtype='float32')
print(npa)

# multidimensional array using list of lists
npa = np.array([range(i, i + 3) for i in [2, 4, 6]])
print(npa)

[1 4 2 5 3]
[3.14 4.   2.   3.  ]
[1. 2. 3. 4.]
[[2 3 4]
 [4 5 6]
 [6 7 8]]


# Creating NumPy Arrays from Scratch
- NumPy provides optimized functions to create ndarrays

In [4]:
# create a 10-integer array filled with zeros
npa = np.zeros(10, dtype=int)
print(npa)

# create a 3x5 floating point array filled with ones
npa = np.ones((3,5), dtype=float)
print(npa)

# create a 3x5 array filled with 3.14
npa = np.full((3,5), 3.14)
print(npa)

# create an array filled with a linear sequence
# starting at 0, ending at 20, stepping by 2
# (similar to built-in range() function)
npa = np.arange(0, 20, 2)
print(npa)

[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
[ 0  2  4  6  8 10 12 14 16 18]


In [5]:
# create a 3x3 array of uniformly distributed
# random values between 0 and 1
npa = np.random.random((3,3))
print(npa)

# create a 3x3 array of normally distributed random
# values with mean 0 and standard deviation 1
npa = np.random.normal(0,1,(3,3))
print(npa)

[[0.88119406 0.92662138 0.31482319]
 [0.24800286 0.22961772 0.4850453 ]
 [0.01258149 0.29347353 0.72973182]]
[[-1.98520783  0.08510529  0.26735146]
 [-1.1154919   0.1265032  -1.5686    ]
 [ 0.45459357  0.15657123 -0.99432048]]


# NumPy Standard Data Types
<img src="images/SWC22-NumPy.standard-data-types.png" align = "left" width=400 height=400 />

# NumPy Array Operations
- NumPy array operations are critical to many Data Science packages
- Array operations include
    - accessing attributes: determining size, shape, memory usage, and data types
    - indexing: getting/setting individual array element values
    - slicing: getting/setting subarrays
    - reshaping: changing an array's shape
    - joining/splitting: combining multiple arrays into one, split one array into multiple

# NumPy Array Attributes

- Useful attributes of NumPy arrays:
    - ndim: number of dimensions
    - shape: size of each dimension
    - size: total size of the array (number of elements)
    - dtype: data type
    - itemsize: size in bytes of one array element
    - nbytes: total size of array in bytes (itemsize * size)


# Displaying NumPy Array Attributes
- Let's use a simple NumPy function to demonstrate how to display an array's attributes:
    - The **random.randint** function creates a NumPy array of random integers as part of a uniform distribution (probability of all values is the same)

In [6]:
dist = np.random.randint(low=1, high=10, size=5, dtype='l')
print(dist)
print(dist.ndim)
print(dist.shape)
print(dist.size)
print(dist.dtype)
print(dist.itemsize)
print(dist.nbytes)

[7 8 4 6 4]
1
(5,)
5
int32
4
20


# 2D NumPy Array Attributes
- The following examples demonstrate the array attributes of various types of NumPy arrays

In [7]:
np.random.seed(0) # seed random generator
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

print("x1: ")
print(x1)

print("x1 ndim: ", x1.ndim)
print("x1 shape: ", x1.shape)
print("x1 size: ", x1.size)

print("x2: ")
print(x2)

print("x2 ndim: ", x2.ndim)
print("x2 shape: ", x2.shape)
print("x2 size: ", x2.size)

print("x3: ")
print(x3)

print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x1: 
[5 0 3 3 7 9]
x1 ndim:  1
x1 shape:  (6,)
x1 size:  6
x2: 
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
x2 ndim:  2
x2 shape:  (3, 4)
x2 size:  12
x3: 
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


# Array Indexing: Single Element, Single Dimension
- NumPy array indexing is similar to Python list indexing, both for accessing and setting single elements

In [8]:
x1 = np.random.randint(10, size=6)
print("x1 = ", x1)
print("x1[0] = ", x1[0])
print("x1[4] = ", x1[4])
print("x1[-1] = ", x1[-1])
print("x1[-2] = ", x1[-2])
x1[1] = 3.14159 # will truncate
print("x1[1] = ", x1[1])
print("x1 = ", x1)

x1 =  [4 3 4 4 8 4]
x1[0] =  4
x1[4] =  8
x1[-1] =  4
x1[-2] =  8
x1[1] =  3
x1 =  [4 3 4 4 8 4]


# Array Indexing: Single Element, Multi-Dimension

In [9]:
x2 = np.random.randint(10, size=(3,4))
print("x2 = \n", x2)
print()
print("x2[0,0] = ", x2[0,0])
print("x2[2,0] = ", x2[2,0])
print("x2[2,-1] = ", x2[2,-1])


x2 = 
 [[3 7 5 5]
 [0 1 5 9]
 [3 0 5 0]]

x2[0,0] =  3
x2[2,0] =  3
x2[2,-1] =  0


# Array Slicing: One Dimension
- NumPy slicing syntax follows that of the standard Python list
- To access a slice of an array x, use x[start:stop:step]
    - If any of these are unspecified, they default to the values
          start=0, stop=(size of dimension), step=1

In [10]:
# slicing
print("x1 = ", x1)
print("x1[:3] = ", x1[:3])    # up to index 3 (excl)
print("x1[3:] = ", x1[3:])    # start at index 3
print("x1[2:5] = ", x1[2:5])  # element index 2 - 4
print("x1[::2] = ", x1[::2])  # every other element
print("x1[::-1] = ", x1[::-1]) # reverse all

x1 =  [4 3 4 4 8 4]
x1[:3] =  [4 3 4]
x1[3:] =  [4 8 4]
x1[2:5] =  [4 4 8]
x1[::2] =  [4 4 8]
x1[::-1] =  [4 8 4 4 3 4]


# Array Slicing: Multi-Dimension
- Multiple-dimension slices are separated by commas

In [11]:
# multi-slicing
print("x2 = \n", x2)
print("x2[:2,:3] = \n", x2[:2, :3]) # 2 rows, 3 columns
print("x2[:3,::2] = \n", x2[:3, ::2]) # all rows, every other column
print("x2[::-1,::-1] = \n", x2[::-1, ::-1]) # reverse rows and columns

x2 = 
 [[3 7 5 5]
 [0 1 5 9]
 [3 0 5 0]]
x2[:2,:3] = 
 [[3 7 5]
 [0 1 5]]
x2[:3,::2] = 
 [[3 5]
 [0 5]
 [3 5]]
x2[::-1,::-1] = 
 [[0 5 0 3]
 [9 5 1 0]
 [5 5 7 3]]


# Accessing Array Rows and Columns
- Combine indexing and slicing to access an entire row or column

In [12]:
print("x2 =\n", x2)
print("x2[:,0]", x2[:, 0])  # first column
print("x2[0,:]", x2[0, :])  # first row
print("x2[0]", x2[0])     # first row (can omit : for row)

x2 =
 [[3 7 5 5]
 [0 1 5 9]
 [3 0 5 0]]
x2[:,0] [3 0 3]
x2[0,:] [3 7 5 5]
x2[0] [3 7 5 5]


# NumPy Arrays as Views
- In contrast to lists, which slice as *copies*, numpy arrays slice as *views*
    - Modifications to a numpy array slice modifies original data in place vs.  modifying a copy of the data, improving performance
    - Use array.copy() as necessary, e.g. to back up original data

In [13]:
print('x2 = ')
print(x2)
x2bak = x2.copy()    # back up x2
x2_sub = x2[:2, :2]  # slice x2 into x2_sub
print('x2_sub (sliced as x2[:2, :2]) = ')
print(x2_sub)
x2_sub[0, 0]= 99     # modify x2_sub
print('x2_sub modified first element:')
print(x2_sub)
print('x2 was also modified:')
print(x2)
x2 = x2bak.copy()    # restore original x2

x2 = 
[[3 7 5 5]
 [0 1 5 9]
 [3 0 5 0]]
x2_sub (sliced as x2[:2, :2]) = 
[[3 7]
 [0 1]]
x2_sub modified first element:
[[99  7]
 [ 0  1]]
x2 was also modified:
[[99  7  5  5]
 [ 0  1  5  9]
 [ 3  0  5  0]]


# Reshaping Arrays
- The reshape() function gives a new shape to an array without changing its data.
    - The size of the initial array must match the size of the reshaped array

In [14]:
# reshape 1D to 2D (3x3)
r = np.arange(1, 10)
print("r = ", r)
grid = r.reshape((3, 3))
print("grid = ")
print(grid)
print('ndim:', grid.ndim, ', shape:', grid.shape)

r =  [1 2 3 4 5 6 7 8 9]
grid = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2 , shape: (3, 3)


In [15]:
# convert 1D array to 2D (3x1)
print('reshape a 1x3 array as 3x1:')
x = np.array([1, 2, 3])
print('x ndim:', x.ndim, ', shape:', x.shape)

y = x.reshape(3, 1)
print('y ndim:', y.ndim, ', shape:', y.shape)
print(y)

reshape a 1x3 array as 3x1:
x ndim: 1 , shape: (3,)
y ndim: 2 , shape: (3, 1)
[[1]
 [2]
 [3]]


# NumPy Arrays vs. Matrices
- You will see references to <ins>matrices</ins> in NumPy operations
    - Note the distinction between an <ins>array</ins> and a <ins>matrix</ins>:
        - **array**
          A homogeneous n-dimensional container (ndarray) of numerical elements
        - **matrix**
          A 2-dimensional ndarray that preserves its two-dimensional nature throughout operations. It has certain special operations, such as * (matrix multiplication) and ** (matrix power)

# Array Concatenation
Three functions are available for concatenating arrays:
- np.concatenate  
- np.vstack  
- np.hstack

<ins>np.concatenate</ins> takes a tuple or list of arrays as its first argument

In [16]:
x = np.array([1, 2, 3])
print('x:')
print(x)

y = np.array([3, 2, 1])
print('y:')
print(y)

print('concatenated:')
print(np.concatenate([x, y]))

x:
[1 2 3]
y:
[3 2 1]
concatenated:
[1 2 3 3 2 1]


# Array Concatenation with np.vstack
- <ins>np.vstack</ins> will concatenate vertically
- useful for arrays with different dimensions

In [17]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
print(np.vstack([x, grid]))

[[1 2 3]
 [9 8 7]
 [6 5 4]]


# Array Concatenation with np.hstack
- <ins>np.hstack</ins> will concatenate horizonally

In [18]:
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
y = np.array([[99],
              [99]])
# horizontally stack the arrays
print(np.hstack([grid, y]))

[[ 9  8  7 99]
 [ 6  5  4 99]]


# Array Splitting
- The opposite of concatenation is splitting, implemented by <ins>np.split</ins>, <ins>np.hsplit</ins>, and <ins>np.vsplit</ins>.
- Each of these accepts a list of indices giving the split points.
- N split points lead to N + 1 subarrays

In [19]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


# Universal Functions
- Standard algorithmic approaches to array manipulation can be very slow when data sets get large.
    - Python's dynamic typing can cause bottlenecks in calculations.
    - Compiled code predetermines types and results are computed much more efficiently.
- NumPy provides an interface into statically typed, compiled routines known as <ins>vectorized</ins> operations, implemented through <ins>universal functions</ins> ("ufuncs"). 
    - ufuncs make repeated calculations on array elements much more efficient

# Universal Functions: Example
- define a function to calculate reciprocals (1 / number) and calculate the time difference between a standard algorithm vs. ufunc

In [20]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
print('values:', values)
print('reciprocals:', compute_reciprocals(values))

values: [2 3 5 3 1]
reciprocals: [0.5        0.33333333 0.2        0.33333333 1.        ]


- Now use the Python timing library to time the reciprocal function on a large data set

In [21]:
import timeit
big_array = np.random.randint(1, 100, size=1000000)
stmt_arg = 'compute_reciprocals(big_array)'
setup_arg = 'from __main__ import compute_reciprocals, big_array'
t = timeit.Timer(stmt=stmt_arg,setup=setup_arg)

print('time to run 5 reciprocal calculations on 1000000 items:')
print(t.timeit(number=5))

time to run 5 reciprocal calculations on 1000000 items:
13.830458999960683


- Finally , modify the compute_reciprocals function to use a vectorized calculation

In [22]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    #for i in range(len(values)):
    #    output[i] = 1.0 / values[i]
    output = 1.0 / values
    return output

# run the timed operation again
print('time to run 5 reciprocal calculations on 1000000 items:')
print(t.timeit(number=5))

time to run 5 reciprocal calculations on 1000000 items:
0.015449899947270751


# uFuncs and Array Arithmetic
- ufuncs make use of Python’s native arithmetic operators. 
    - Standard addition, subtraction, multiplication, and division can all be used

In [23]:
x = np.arange(4)
print(x)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)

[0 1 2 3]
x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


# uFunc Arithmetic Operators
- Arithmetic operations in NumPy are actually wrappers around specific functions built into NumPy
- For example, the + operator is a wrapper for the add function

In [24]:
print(np.add(x, 2))

[2 3 4 5]


# uFuncs And Arrays
- ufuncs can be used for operations on multiple arrays

In [25]:
print(np.arange(5))
print(np.arange(1, 6))
print(np.arange(5) / np.arange(1, 6))
print(np.arange(1, 6).dtype)
print((np.arange(5) / np.arange(1, 6)).dtype)

[0 1 2 3 4]
[1 2 3 4 5]
[0.         0.5        0.66666667 0.75       0.8       ]
int32
float64


# uFuncs And Multi-Dimensional Arrays
- ufuncs can be used for operations on multi-dimensional arrays


In [26]:
x = np.arange(9).reshape((3, 3))
print('x:\n', x)
print('2 ** x:\n', 2 ** x)

x:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
2 ** x:
 [[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]


# Specifying Output
- For large calculations, rather than creating a temporary array, you can improve performance by writing computation results directly to a predefined memory location.
    - For all ufuncs, you can do this using the out argument of the function

In [27]:
x = np.arange(5)
y = np.empty(5)
print(x)
np.multiply(x, 10, out=y)
print(y)

[0 1 2 3 4]
[ 0. 10. 20. 30. 40.]


# Specifying Output: Views
- The **out** argument can also be used with array views. 
    - For example, to write the results of a computation to every other element of a specified array:

In [28]:
y = np.zeros(10)
print(x)
np.power(2, x, out=y[::2])
print(y)

[0 1 2 3 4]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


- Using the more generic expression y[::2] = 2 ** x would have created a temporary array to hold the results of 2 ** x, followed by a second operation copying those values into the y array.
    - This is fine for a small computation but for very large arrays the memory and performance savings from using the out argument can be significant.

# Aggregates
- Aggregates (e.g. combinations or summaries) can be computed directly from the NumPy objects. 
- Reducing an array means repeatedly applying a given operation to the elements until only a single result remains.
    - For example, chaining reduce to the add and multiply ufuncs returns the sum/product of all elements in the array:

In [29]:
x = np.arange(1, 6)
print(x)
print(np.add.reduce(x))
print(np.multiply.reduce(x))

[1 2 3 4 5]
15
120


# Accumulating Aggregation Operations
We can store intermediate results of the computations using the <ins>accumulate</ins> function:

In [30]:
print(x)
print(np.add.accumulate(x))
print(np.multiply.accumulate(x))

[1 2 3 4 5]
[ 1  3  6 10 15]
[  1   2   6  24 120]


# Aggregates as Summary Statistics
- A first step in analyzing large data sets  is the computation of summary statistics. 
    - Some common summary statistics include the mean, standard deviation, sum, product, median, minimum and maximum, quantiles, etc.
- NumPy has fast built-in aggregation functions for calculating summary statistics
    - Python has many of these functions as well, but they do not use compiled code and are much slower

In [31]:
x = np.random.random(1000000)
print(np.sum(x))  # sum
print(np.mean(x)) # average
print(np.std(x))  # standard deviation

500218.87607282447
0.5002188760728244
0.28885012100374347


# Aggregates: Object Method Alternatives
The NumPy summary functions are also provided through the object itself:

In [32]:
print(x.sum())
print(x.mean())
print(x.std())
print(x.min())
print(x.max())

500218.87607282447
0.5002188760728244
0.28885012100374347
7.071203171893359e-07
0.9999997207656334


# Multi-Dimensional Aggregates
By default, each NumPy aggregation function will return the aggregate over the entire array, including multiple dimensional arrays:

In [33]:
m = np.random.random((3, 4))
print(m)
print(m.sum())

[[0.37819162 0.41254334 0.96707041 0.78393884]
 [0.25476293 0.47361973 0.50219341 0.36082531]
 [0.79186763 0.31353191 0.14772955 0.08458909]]
5.470863775483883


# Aggregating on an Axis
- To calculate aggregates along specific dimensions we use the axis argument
- A NumPy axis is an element of the shapes attribute
    - 0 is the first axis (e.g. the row dimension of a matrix)
    - 1 is the second axis (e.g.  the column dimension of a matrix)
    - higher numbers correspond to the index of the shape attribute element
- The operation is performed by collapsing the array along the specified axis and performing the specied operation

<img src="images/SWC22-NumPy-aggregate-axes.png" align = "left" width=500 height=500/>

In [34]:
m = np.array([[3,4,5],[7,8,9],[22,21,20]])
print(m.shape)
print(m.sum())
print(m.sum(axis=0))
print(m.sum(axis=1))

(3, 3)
99
[32 33 34]
[12 24 63]


In [ ]:
# Find the minimum value within each column and
# the maximum value within each row of a matrix:
m = np.random.random((3, 4))
print(m)
print('min in each col = ', ________)
print('max in each row = ', ________)

In [41]:
m = np.random.random((3, 4))
print(m)
print('min in each col = ', m.min(axis=0))
print('max in each row = ', m.max(axis=1))

[[0.90657413 0.18671025 0.07262851 0.0068539 ]
 [0.07533272 0.77114754 0.94502816 0.79396332]
 [0.81250458 0.68306202 0.09142216 0.72943166]]
min in each col =  [0.07533272 0.18671025 0.07262851 0.0068539 ]
max in each row =  [0.90657413 0.94502816 0.81250458]


# Computation on Arrays: Broadcasting
- Another important concept in vectorizing operations is NumPy’s <ins>broadcasting</ins> feature.
- Broadcasting is simply a set of rules for applying ufuncs to arrays of different sizes.
- For arrays of the same size, binary operations are performed on an element-by-element basis:

In [42]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
print(a + b)

[5 6 7]


## Consider adding a scalar ("zero-dimensional array" – a single number) to an array
- Think of this as an operation that "stretches" or duplicates the value into the array, then adds the results. 
    - The duplication of values does not actually take place, but is a useful mental model for thinking about broadcasting.
    - e.g. a 1 x 3 array

In [43]:
a = np.array([0, 1, 2])
print(a + 5)

[5 6 7]


## In most calculations, the smaller array is stretched, or broadcast across the larger array so that they have compatible shapes. 
- e.g. add a one-dimensional array to a two-dimensional array:
    - Here the one-dimensional array a is broadcast across the second dimension in order to match the shape of m

In [46]:
a = np.array([0, 1, 2])
m = np.ones((3, 3))
print(a, "\n")
print(m, "\n")
print(m + a)

[0 1 2] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


## More complicated cases can involve broadcasting of both arrays.

In [48]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a, "\n")
print(b, "\n")
print(a + b)

[0 1 2] 

[[0]
 [1]
 [2]] 

[[0 1 2]
 [1 2 3]
 [2 3 4]]


- Previously, one value was broadcast to match the shape of the other, but here both a and b have been stretched to match a common shape, and the result is a two-dimensional array

## An array must have a dimension of 1 in order to be "stretchable", which means not all array shapes can be broadcast.
- In the following example neither array can be broadcast onto the other because neither has a dimension of 1, so the operation fails

In [49]:
m = np.array(([2,4,6],[3,4,5]))
print(m, "\n")
[[2, 4, 6],       # 2 x 3
 [3, 4, 5]]
n = np.array(([1,2],[1,2],[1,2],[1,2]))
print(n, "\n")
[[1, 2],          # 4 x 2
 [1, 2],
 [1, 2],
 [1, 2]]
print(m + n)

[[2 4 6]
 [3 4 5]] 

[[1 2]
 [1 2]
 [1 2]
 [1 2]] 



ValueError: operands could not be broadcast together with shapes (2,3) (4,2) 

# Comparisons, Masks, and Boolean Logic
- Boolean <ins>masks</ins> can be used to examine and manipulate values within NumPy arrays. 
    - Masking is useful to extract, modify, count, or otherwise manipulate values in an array based on some criterion

In [54]:
x = np.array([1, 2, 3, 4, 5])
print("\t\t\t", x)
print("less than 3?\t\t", x < 3)
print("greater than 3?\t\t", x > 3)
print("not equal to 3?\t\t", x != 3)
print("equal to 3?\t\t", x == 3)
print("2x = square?\t\t", (2 * x) == (x ** 2))

			 [1 2 3 4 5]
less than 3?		 [ True  True False False False]
greater than 3?		 [False False False  True  True]
not equal to 3?		 [ True  True False  True  True]
equal to 3?		 [False False  True False False]
2x = square?		 [False  True False False False]


# Working with Masks
- Counting entries
- How many values are less than 6?

In [56]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
print(x, "\n")
print(np.count_nonzero(x < 6))

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

8


- "nonzero" as used here in the method **count_nonzero()** does not refer to numerical values in the original array, but instead refers to the numeric values of 1 (True) and 0 (False) in the logical Boolean array resulting from applying the condition x < 6